# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vmCYcGoQNJILsm-IUxPsE4OKHCkmdou7
"""

import streamlit as st
import pandas as pd
import joblib

st.set_page_config(page_title="SmartAllot Score Predictor", page_icon="📊", layout="centered")

# Load artifacts
@st.cache_resource
def load_artifacts():
    preprocessor = joblib.load("preprocessor.pkl")
    scaler = joblib.load("scaler.pkl")
    model = joblib.load("best_model.pkl")
    columns = joblib.load("columns.pkl")
    return preprocessor, scaler, model, columns

preprocessor, scaler, model, FEATURE_COLUMNS = load_artifacts()

st.title("📊 SmartAllot Score Predictor")
st.caption("Upload a CSV without scores → get it back with predicted scores")

st.divider()

st.subheader("Required columns")
st.write(f"**{', '.join(FEATURE_COLUMNS)}**")
st.info("Gender column is optional (not used for scoring but kept for reference).")

uploaded = st.file_uploader("Upload CSV", type=["csv"])

if uploaded:
    try:
        df = pd.read_csv(uploaded)
        st.write(f"Rows: {len(df)} | Columns: {list(df.columns)}")

        missing = [c for c in FEATURE_COLUMNS if c not in df.columns]
        if missing:
            st.error(f"Missing required columns: {', '.join(missing)}")
        else:
            X = df[FEATURE_COLUMNS]
            X_processed = preprocessor.transform(X)
            X_scaled = scaler.transform(X_processed)
            scores = model.predict(X_scaled)

            result_df = df.copy()
            result_df["Score"] = scores.round(2)

            st.success(f"Scored {len(result_df)} rows successfully.")
            st.dataframe(result_df.head(20), use_container_width=True, hide_index=True)

            csv_bytes = result_df.to_csv(index=False).encode("utf-8")
            st.download_button(
                "⬇️ Download scored CSV",
                data=csv_bytes,
                file_name="scored_output.csv",
                mime="text/csv",
            )
    except Exception as e:
        st.error(f"Error: {e}")

st.divider()
st.caption("SmartAllot • Hostel Allocation System")